myblog/myblog/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('templates/',include('templates.urls')),
    path('templatesapi/', include('templates_api.urls')),
]

myblog/templates/urls.py
from django.urls import path

from . import views
app_name = 'templates'

urlpatterns = [
    path('',views.index, name = 'index'),
    path('newblog/',views.newblog, name = 'newblog'),
    path('createblog/',views.blogFunc, name = 'createblog'),
    path('<int:id>/editblog/',views.updateblog, name = 'editblog'),
    path('<int:id>/save/',views.save, name = 'save'),
    path('<int:id>/delete/',views.delete, name = 'delete'),

]

myblog/templates_api/urls.py
from django.urls import path

from . import views

app_name = 'templates_api'

urlpatterns = [
    path('blogs/', views.blog_list),
    path('blogs/<int:id>/', views.blog_detail),

]

myblog/templates/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title  = models.CharField(max_length = 200)
    body = models.CharField(max_length = 200)
    created_at = models.CharField(max_length = 200)

myblog/templates_api/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title  = models.CharField(max_length = 200)
    body = models.CharField(max_length = 200)
    created_at = models.CharField(max_length = 200)

    def to_json(self):
        return{
            'id': self.id,
            'title':self.title,
            'body':self.body,
            'created_at':self.created_at
        }

myblog/templates/views.py
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse, QueryDict
from django.template import loader
from django.http import Http404
from .models import Blog
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def index(request):
    blog_list = Blog.objects.all
    return render(request, 'blog/index.html',{'blog_list':blog_list})
def blogFunc(request):
    return render(request,'blog/blog.html',{'blog_list':Blog.objects.all})

def newblog(request):
    title = request.POST['title']
    body = request.POST['body']
    created_at = request.POST['created_at']
    b = Blog.objects.create(title = title, body = body, created_at = created_at)
    return HttpResponseRedirect(reverse('templates:index'))
def updateblog(request, id):
    title = Blog.objects.get(pk = id).title
    body = Blog.objects.get(pk=id).body
    created_at = Blog.objects.get(pk=id).created_at

    return render(request, 'blog/edit.html',{'title':title,'body':body,'created_at':created_at,'id':id,'blog_list':Blog.objects.all})
def save(request, id):
    title = request.POST['title']
    body = request.POST['body']
    created_at = request.POST['created_at']
    Blog.objects.filter(pk=id).update(title=title, body=body, created_at = created_at)
    return HttpResponseRedirect(reverse('templates:index'))
def delete(request, id):
    Blog.objects.filter(pk=id).delete()
    return HttpResponseRedirect(reverse('templates:index'))

myblog/templates_api/views.py
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse,HttpResponseRedirect, JsonResponse
from rest_framework.parsers import JSONParser
from django.views.decorators.csrf import csrf_exempt
from django.template import loader
from django.http import Http404
from .models import Blog
from django.urls import reverse



@csrf_exempt
def blog_list(request):
    if request.method == "GET":
        blog_list = Blog.objects.all()
        blog_list_json = [b.to_json() for b in blog_list]
        return JsonResponse(blog_list_json, safe=False)

    elif request.method == "POST":
        data = request.POST
        blog = Blog()
        blog.title = data.get('title','')
        blog.body = data.get('body','')
        blog.created_at = data.get('created_at','')
        blog.save()
        return JsonResponse(blog.to_json(), status = 201)

@csrf_exempt
def blog_detail(request,id):
    try:
        blog = Blog.objects.get(pk=id)
    except Exception as e:
        return JsonResponse({"error": str(e)}, status=404)

    if request.method == "GET":
        return JsonResponse(blog.to_json())
    elif request.method == "PUT":
        data = QueryDict(request.body)
        blog.title = data.get('title', blog.title)
        blog.body = data.get('body', blog.body)
        blog.created_at = data.get('created_at', blog.created_at)
        blog.save()
        return JsonResponse(blog.to_json())
    elif request.method == "DELETE":
        blog.delete()
        return JsonResponse(blog.to_json())

myblog/templates/templates/blog/blog.html
{% load static %}
<h1>Add blog</h1>
<form action = "{% url 'templates:newblog'  %}" method = "post" class="needs-validation">
  {% csrf_token %}
  <div >
    <label for="text">Title</label>
    <input class="form-control" type = "text" name="title" id = "title" value = ""/>
  </div>
  <br/>
  <div >
    <label for="text">Body</label>
    <input class="form-control" type = "text" name="body" id = "body" value = ""/>
  </div>
  <br/>
  <div >
    <label for="text">Created at</label>
    <input class="form-control" type = "text" name="created_at" id = "created_at" value = ""/>
  </div>
  <br/>

  <input type = "submit" value = "submit" />
</form>

myblog/templates/templates/blog/edit.html
{% load static %}
<h1>Edit blog</h1>
<form action = "{% url 'templates:save' id  %}" method = "post" class="needs-validation">
  {% csrf_token %}
  <div >
    <label for="text">Title</label>
    <input class="form-control" type = "text" name="title" id = "title" value = "{{title}}"/>
  </div>
  <br/>
  <div >
    <label for="text">Body</label>
    <input class="form-control" type = "text" name="body" id = "body" value = "{{body}}"/>
  </div>
  <br/>
  <div >
    <label for="text">Created at</label>
    <input class="form-control" type = "text" name="created_at" id = "created_at" value = "{{created_at}}"/>
  </div>
  <br/>

  <input type = "submit" value = "submit" />
</form>
<form action = "{% url 'templates:delete' id %}" method = "post">
  {% csrf_token %}
  <input type = "submit" value = "Delete" />
</form>

myblog/templates/templates/blog/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'todo_demo/style.css' %}" />
<h1>Blog</h1>
<ul >
  {% for item in blog_list%}
  <li >
    <div >
      <p >Title: 
        {{item.title}}
      </p>
      <p >Body:
        {{item.body}}
      </p>
      <p >Created at:
        {{item.created_at}}
      </p>
  </div>

  <form action = "{% url 'templates:editblog' item.id  %}" method = "post">
    {% csrf_token %}
    <input type="submit" value="Edit"  />
  </form>

    </li>
  {% endfor %}
</ul>
<form action = "{% url 'templates:createblog' %}" method = "post">
  {% csrf_token %}
  <input type="submit" value="Add"  />
</form>